server:
  port: 8080

spring:
  application:
    name: livestock-ai
  autoconfigure:
    exclude:
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration
      - org.springframework.ai.model.openai.autoconfigure.OpenAiAutoConfiguration

livestock:
  ai:
    mode: ollama
  demo:
    enabled: false
    interval: 3s
  real-feed:
    enabled: true

news:
  api:
    key: ${NEWS_API_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
